sindresorhus/awesome-nodejs

readme.md

Added nmotw.

---

readme.md

As promised [here](https://github.com/sindresorhus/awesome-nodejs/pull/230) implemented Hapi support in [version 2.0.1](https://www.npmjs.com/package/grant)

Update Grant support for Hapi

---

readme.md

Since `got` now have all of `sent` features and more it is time to remove it.

Remove sent

---

readme.md

This adds [x-ray](https://github.com/lapwinglabs/x-ray), a web scraping utility with the following features:
- Flexible schema: Supports strings, arrays, arrays of objects, and nested object structures. The schema is not tied to the structure of the page you're scraping, allowing you to pull the data in the structure of your choosing.
- Pagination support: Paginate through websites, scraping each page. X-ray also supports a request delay and a pagination limit. Scraped pages can be streamed to a file, so if there's an error on one page, you won't lose what you've already scraped.
- Complex actions: With the PhantomJS driver, you can click on buttons, fill out forms, even login or signup before scraping the page. This allows you to scrape pages that require authentication like Facebook or …

Add x-ray to Parsing

---

readme.md

This one was found, when i searched replacement for Revalidator due incomplete standard support (needed to describe several allowed objects in array content).
[is-my-json-valid](https://github.com/mafintosh/is-my-json-valid) really supports almost all spec features and has very high speed as bonus (it generates native function for each schema).

Add `is-my-json-valid`

---

readme.md

nearley is the first JS parser to use the Earley algorithm and processes left recursion without choking

Add `nearley`

---

readme.md

Another css postprocessor. More info: http://stylecow.github.io/

Added stylecow

---

readme.md

http://faye.jcoglan.com/
I think, it's one of 3 "elephant" for realtime messaging (socket.io, sockjs, faye). If you have link to socket.io & sockjs, faye should not be missed.

Add `Faye`

---

readme.md

http://catberry.org/
https://github.com/catberry/catberry
I think it's worth to be mentioned in the list. This framework allows building isomorphic applications using component-based approach. Also, it has progressive rendering which allows application's user to see the content with a minimal delay (streaming-based rendering at the server and step-based rendering in a browser).
It is well tested (~91% coverage) and documented.

Add Catberry Framework to the list

---

readme.md

I think that it would be wonderful to list this resource as it has chapters on globals, buffers, events, streams, the file system, networking, child processes, and more.
http://www.manning.com/young/

Add Node.js in Practice

---

readme.md

RobotJS is awesome, and has a lot of potential. I looked through all of the categories and couldn't really find a good place to put it, so I am proposing an "automation" category for it.

added robotjs

---

readme.md

This is library I've started by frustration of how painful usage of pure `fs` sometimes could be.
Just reached enough maturity to be used by wider audience and check if this idea holds water.

Added fs-jetpack

---

readme.md

[repo](https://github.com/wooorm/alex) | [demo](http://alexjs.com).
:heart:

Add `alex`

---

readme.md

Created "URL" section

---

readme.md

Hi,
I've just released a simple Markdown previewer working with Node.js. I use it everyday, and hope it can help others too.
https://github.com/noraesae/pen
Thanks :smile:

Add pen, a Markdown previewer.

---

readme.md

Hi,
I have made a CLI utility to download subtitles for movies and TV series.
you just have to execute a simple command to download subtitles for one or more file at a time.
I am using it daily and its very helpful hope it can help others too
https://github.com/beatfreaker/subdownloader
Thanks :smiley:

Add subdownloader

---

readme.md

This adds [trevor](https://github.com/vdemedes/trevor).
It allows to run tests against multiple versions of Node.js using the same configuration file used by Travis CI (`.travis.yml`).
With trevor you can run the tests locally before pushing the code to the remote repository, without switching the node versions manually on your local environment.

Add trevor to Testing

---

readme.md

add - [Pro Express.js](http://proexpressjs.com)

add Pro Express.js

---

readme.md

I was going to propose this later on as it matured, but it's currently trending in the top 5 on HN, so thought now would be a good time, if that's okay with you. :)

Add Vorpal

---

contributing.md

See https://github.com/sindresorhus/awesome-scifi/pull/174 for rationale.

Added section on updating a PR

---

readme.md

[multispinner](https://github.com/codekirei/node-multispinner)
A module for creating multiple, simultaneous, individually controllable CLI spinners. Uses your `log-update` module as the core (...and `chalk` ...and `figures` :flushed:).
Specifically intended as a convenience module for CLI apps that execute concurrent tasks with something like `Promise.all()` (e.g. downloading multiple docker images or writing multiple files). `multispinner` makes it simple to create a group of spinners for concurrent tasks and live update each spinner (with success/failure) as its task finishes.
Lots of handy configurable options and events baked in. 100% test coverage and fully documented API.

add multispinner

---

readme.md

Anthony Alicea is an excellent instructor and his course has 356 reviews with 4.9 average rating and 8915 students (me too) enrolled in course up to this commit time.

Add a course link

---

readme.md

There are all sorts of webpack loaders and you can write your own.

Extend webpack's description

---

readme.md

Rename mdast to remark

---

readme.md

[mobicon-cli](https://github.com/samverschueren/mobicon-cli) add to the list of `Command-line apps`.
No problem if you reject it :).

add mobicon to cli apps

---

readme.md

Added [mobisplash](https://github.com/samverschueren/mobisplash-cli) to the list.

add mobisplash

---

readme.md

Added [tz-format](https://github.com/samverschueren/tz-format) to the `Date` list.

add tz-format

---

readme.md

Daily injection of npm packages:
https://npmaddict.com

Add npm addict

---

readme.md

`property-validator` is a property validation library built on top of `validator.js` to help developers validate request, query, body params and request headers.

add property-validator

---

readme.md

Add Mostly Node podcast

---

readme.md

I have read this book recently and I think it's the best thing, where you can find security tips and tricks with good explanation.

Add "Secure Your Node.js Web Application" book

---

readme.md

- [hypernova](https://github.com/airbnb/hypernova) - A service for server-side rendering your JavaScript views.

Add Hypernova

---

readme.md

Aerospike is a distributed NoSQL database and key-value store. The aerospike npm package provides a Node.js client library to connect to an Aerospike server cluster. The client library and the Community Edition of the server are open source.
Aerospike Homepage: http://www.aerospike.com/
npm package: https://www.npmjs.com/package/aerospike
Github repo: https://github.com/aerospike/aerospike-client-nodejs

Add Aerospike DB client

---

readme.md

https://github.com/SkyHacks/nerds
Awesome library for adding mock data to sample apps, presentations, etc from your favorite geeky shows, movies, and hobbies. 100% code coverage and still being actively developed.

Add `nerds`

---

readme.md

Provides a simple and flexible way to search the filesystem. 
Source:
https://github.com/nspragg/filehound

Add filehound

---

readme.md

A Rest client that has been built for resilience and is easy to use. 
Source:
https://github.com/bbc/flashheart

Add flashheart

---

readme.md

Auto installs dependencies as you code.
Source:
https://github.com/siddharthkp/auto-install

Add auto-install

---

readme.md

Add Phenomic

---

readme.md

#588 
I've added link under `mem` now. May be it could be better in promise section https://github.com/sindresorhus/awesome-nodejs#control-flow, let me know if i should move.

Add `promise-memoize`

---

readme.md

https://github.com/mqttjs/MQTT.js

Add MQTT.js

---

readme.md

[ActionHero](http://www.actionherojs.com/) - Framework for making reusable & scalable APIs for TCP sockets, WebSockets, and HTTP clients.

Add ActionHero

---

readme.md

*A guide to writing useful READMEs for your Node modules.*
https://github.com/noffle/art-of-readme
I wrote this article over the course of the last four months. It's the accumulation of examining many hundreds of Node modules' READMEs over the course of a few years, writing dozens of my own READMEs, digging into Perl's history of documentation, and my personal thoughts.

Add article: Art of README

---

readme.md

Add seedshot project to mad science section in readme.md
**Seedshot** is peer to peer screenshot sharing from your browser.

Add seedshot

---

readme.md

A highly scalable web socket library with a benchmark table. More info here: [Hackernews discussion](https://news.ycombinator.com/item?id=12905939#12906875)

Add uWebSockets

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Good resource, for learning more about Expressjs. Introduced me to some tips on working with Expressjs that I never came across internet while learning.

Add "Express in Action" to Books

---

readme.md

Add Couchbase to Database section

---

readme.md

As it probably has been split later to a separate package.

Updated link for wifi-password CLI package

---

readme.md

Update "Real Time Web with Node.js" link

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Add `date-fns` utility lib to awesome collection

Add date-fns

---

readme.md

Add Nuxt.js

---

readme.md

Hashnode nodejs is a quick drip nodejs community for those who want a faster post rate than the Reddit, and a less formal question asking place than the Stack Overflow. A community of almost 10k, very active and helpful when wanting to see the newest of Node or ask a quick question to get a quick response. LINK: https://hashnode.com/n/nodejs
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add Hashnode Node.js channel

---

readme.md

[spi-device](https://github.com/fivdi/spi-device) may not have a lot of stars (yet?), but there's nothing else in the list for SPI serial bus access :).

Add spi-device

---

readme.md

Add xlsx-populate

---

readme.md

adding fusebox to the build / bundling tools:
> [FuseBox](https://github.com/fuse-box/fuse-box) - Extremely fast build system that combines the power of webpack, JSPM and SystemJS, with first-class typescript support.

Add FuseBox

---

readme.md

Add docsify

---

readme.md

Now, this is the first minute that the project became "Mature".
This might look like the existing `log-update`, but it's much better, by offering a more simple and api that accepts multiple updates concurrently.
The Gif says what it can do, and the docs even more: [https://github.com/ivanseidel/node-draftlog](https://github.com/ivanseidel/node-draftlog)
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add DraftLog

---

readme.md

[zeit/pkg](https://github.com/zeit/pkg): cross-platform Node.js scripts/apps packaging with dependencies and assets.

Add `pkg` to Build tools section

---

readme.md

Adonis is a true MVC framework for Nodejs with basics done right. It borrows the concept the of Service providers from popular PHP framework Laravel to write scalable applications and also leverage the power of ES6 to make your code expressive and maintainable.

Add AdonisJs

---

readme.md

Update Kalm URL

---

readme.md

[Leakage](https://github.com/andywer/leakage) is a tool for memory leak testing in node. The difference to most other tools is that it does not only give you debugging information, but allows you to write actual tests (like integration tests).
You can actually show that some code does not leak and you can write regression tests. It also means moving away from "how to use tool X to debug a memory leak manually" to a structured test-driven approach.
<p align="center">
</p> …

Add leakage

---

readme.md

Added Node-Resque to the Job Queues list
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add node-resque

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
It's exactly like the description written on the [blog page](https://zeit.co/blog/next).
> We're very proud to open-source Next.js, a small framework for server-rendered universal JavaScript webapps, built on top of React, Webpack and Babel, which powers this very site!

Update Next.js description

---

readme.md

Hemera is a small wrapper around the NATS driver it provides an easy and powerful way to develop microservices. NATS is a simple, fast and reliable solution for the internal communication of a distributed system.
Website https://hemerajs.github.io/hemera-site/
Documentation https://hemerajs.github.io/hemera/
**By submitting this pull request, I promise I have read the contribution guidelines twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add Hemera

---

readme.md

Add abstruse

---

readme.md

Add email-templates

---

readme.md

https://github.com/simonepri/credential-plus

Add credential-plus

---

readme.md

Add `Node.js 8 the Right Way`

---

readme.md

Add github-npm-stats

---

readme.md

Add cacheable-request

---

contributing.md

Update `ammending-a-commit-guide.md` link

---

readme.md

Fix link to Folktale.js

---

readme.md

Add parcel to Build tools
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add parcel

---

readme.md

[Link to project](https://github.com/mjswensen/themer)
I know the bar for command-line apps is especially high. Hopefully [themer](https://github.com/mjswensen/themer) can fall into that category!
Additional information about themer:
* [website](https://themer.mjswensen.com/)
* [HackerNews discussion](https://news.ycombinator.com/item?id=16021874)
* [reddit discussion](https://www.reddit.com/r/programming/comments/7sn8hv/themer_generate_themes_for_your_entire/)
(themer's GUI wrapper is added to your [Electron apps Product Hunt list](https://www.producthunt.com/@sindresorhus/collections/electron-apps), @sindresorhus 🙂)

Add themer

---

readme.md

Updated name and url for ApostropheCMS

---

readme.md

I added my [Moleculer](https://moleculer.services/) project.

Add Moleculer

---

readme.md

Hello,
I was wondering if you would consent to add three books to your books list: Cross-Platform Desktop Applications, Get Programming with Node.js, and Node.js in Action, Second edition.
Thank you for your consideration.

Update `Node.js in Action` book to the second edition

---

readme.md

Added section for serialization libraries.
The first three are well established protocols and their most popular implementations.
The last, [Compactr](https://github.com/compactr/compactr.js) is developed by me and is gaining quick traction. It has already been [featured](https://nmotw.in/compactr/) and has been presented at a few events. It has found it's niche with game developers and has been battle-tested for almost 2 years now.

Add Serialization section

---

readme.md

Add TypeORM

---

readme.md

Update Kefir.js link

---

readme.md

I think it's better known than the two mentioned i18n packages.
PS. Should we start a new i18n category?
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add i18next

---

readme.md

[env-dot-prop](https://github.com/simonepri/env-dot-prop) was heavily inspired from [dot-prop](https://github.com/sindresorhus/dot-prop)

Add env-dot-prop

---

readme.md

It's a MongoDB based job scheduler.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Fix typo in `agenda` description

---

readme.md

Update `Start` link and description

---

readme.md

for context see https://github.com/jamestalmage/cli-table2/issues/43

Replace the unmaintained `cli-table` with `cli-table3`

---

readme.md

Re: Code of conduct bullet regarding existing items in the list
The nodebestpractices repository is better than the existing best practices resource as our content is much larger, and is a result of collaboration of the community, as opposed to one maintainer. That resource also seems to be out of date.
https://github.com/i0natan/nodebestpractices
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add Node.js Best Practices

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
A minor change that adds [taskbook](https://github.com/klauscfhq/taskbook) 😄

Add taskbook

---

readme.md

TypeGraphQL is a modern framework for creating GraphQL APIs in Node.js.
It's designed with type safe in mind (using TypeScript), so you create your GraphQL schema using only classes and decorators.
Additional features like dependency injection, validation or auth guards help with common task that otherwise would require lots of manual work.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add TypeGraphQL

---

readme.md

Hi,
I'm the author of Mongo Seeding - ultimate tool for populating MongoDB database. This is a project that I'm developing from a while ago (11.2017), but it's not popular (I haven't promoted it yet). There are some alternatives, but they are bare-bones - that's why I've started my own project. Let me know what you think!
Best regards,
Pawel
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add Mongo Seeding

---

readme.md

Add rpc-websockets

---

readme.md

Remove node-orm2

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
[YodaOS](https://github.com/yodaos-project/yodaos) is a modern operating system for next generation interactive device, and it uses JavaScript as the application language and support Node.js. For complete description, please see https://medium.com/@yorkienell/yodaos-a-modern-os-for-node-js-community-1d0c068218e4.

Add YodaOS

---

readme.md

Practical guide on how to write portable/cross-platform Node.js code: https://github.com/ehmicky/portable-node-guide
There are currently very few guides about this important topic. The only ones covering the topic in full I found are https://github.com/ehmicky/portable-node-guide#further-reading, i.e. only 3 other links.
The guidelines were tested on Windows, Mac and Linux.
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖** yes I did.

Add Portable Node.js guide

---

readme.md

This page helps us find the version of that module on npm match range.

Add `npm semver calculator`

---

readme.md

Add cherow

---

readme.md

add rate-limiter-flexible to Security section. Rate limit by key and protection from DDoS and brute force attacks in process Memory, Cluster or PM2, Redis, Memcached, MongoDb, MySQL, PostgreSQL
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add rate-limiter-flexible

---

readme.md

Add talk about the V8 garbage collector

---

readme.md

Add Strong Node.js

---

readme.md

Pure JavaScript library for working with MP4 and FLV video files and creating MPEG-TS chunks for HLS streaming.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add node-video-lib

---

readme.md

Adds https://github.com/gajus/slonik.

Add slonik

---

readme.md

Because `Day.js` is the same `Moment.js`, I add it under `Moment.js`

Add `Day.js`

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
[RedisSMQ](https://github.com/weyoss/redis-smq) is a simple high-performance Redis message queue that comes with [real-time monitoring](https://github.com/weyoss/redis-smq/tree/master/screenshots).
For more details see [https://medium.com/@weyoss/building-a-simple-message-queue-using-redis-server-and-node-js-964eda240a2a](https://medium.com/@weyoss/building-a-simple-message-queue-using-redis-server-and-node-js-964eda240a2a)

Add RedisSMQ

---

readme.md

Added Get Programming with Node.js to book list, a great resource for learning how to build web servers using JavaScript and Node.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add book "Get Programming with Node.js"

---

readme.md

As far as I know, this is the only FTP client library that warns about using FTP right at the top of its [README](https://github.com/patrickjuchli/basic-ftp). It’s 2019, don’t use it and stay safe.
But it’s still out there. You might not come across it in modern cloud environments but you’d be surprised where it still is being used and how critical some of the contexts are. At least I was when I faced the situation of having to use it some time ago.
The other surprise was how lacking the current offerings for Node.js are: FTP/S may be legacy tech but there should be a reliable, modern and maintained client library for Node.js that has been written with readers in mind.
This library offers explicit FTP over TLS, supports IPv6, has a Promise-based API, extensive documentation, focuses on …

Add basic-ftp

---

readme.md

- "whether a package name is available" -> "a package name's availability"
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Improve a description

---

readme.md

Adding NodeJS Discord Server
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add Discord server

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
NLP.js is a general natural language set of utilities for nodejs. It has support for 27 languages. It incorporates Intent recognition, Entity extraction, Sentiment Analysis, Language detection and others...
It also has it's own dashboard https://github.com/axa-group/nlp.js-app

Add nlp.js 

---

readme.md

Add CodeceptJS

---

readme.md

Add sqs-consumer

---

readme.md

Remove kue (no longer maintained)

---

readme.md

Add article about Express + GraphQL

---

readme.md

Global HTTP/HTTPS proxy agent configurable using environment variables.
GitHub link: https://github.com/gajus/global-agent

Add global-agent

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
I have tried out several node environment managers and none of them have worked as easily and simply as nodenv. The ability to automatically switch node versions is a huge convenience.
https://github.com/nodenv/nodenv/wiki/Why-nodenv%3F

Add nodenv

---

readme.md

Useful QRCode generator which can be used as CLI tool, module (both for node and browser)

Add qrcode

---

readme.md

I looked through different job queue systems for my standalone, desktop app, and found this one, which does the job (so to speak) quite well, and it doesn't need me to install/embed Redis. It's simple and efficient and perfect for small workloads when you need a queue system (for example to manage a download queue)

Add better-queue

---

readme.md

Github link: https://github.com/sfninja/thetool
> thetool is a CLI tool to capture different cpu, memory and other profiles for your node app in Chrome DevTools friendly format.
Please check [readme.md](https://github.com/sfninja/thetool#readme) for more details.

Add thetool

---

readme.md

Update `ajv` description

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
See: https://github.com/davesag/jose-simple
Added under `#security`

Add jose-simple

---

readme.md

Add Puppeteer

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Build a real webapp with no frameworks
https://github.com/mtimofiiv/frameworkless

Add frameworkless tutorial series

---

readme.md

Trace API calls and Monitor API performance, health and usage statistics.
With statistics and metrics exposed by swagger-stats you may spot problematic API endpoints, see where most of errors happens, catch long-running requests, analyze details of last errors, observe trends, setup alerting.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add swagger-stats

---

readme.md

Easily find and remove old and heavy node_modules folders
https://github.com/voidcosmos/npkill
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add npkill

---

readme.md

because this project is DEPRECATED

Remove MERN

---

readme.md

Add link to "10 Things I Regret About Node.js"

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
GitHub: https://github.com/ForbesLindesay/atdatabases
Website: https://www.atdatabases.org
`@databases` is a collection of packages that allow querying SQL databases with raw SQL without risk of SQL Injection vulnerabilities via the use of template literals. The template literal protection gives them a significant security upgrade relative to the low level database drivers and the raw SQL makes them more powerful and gives users more transferable skills than using the …

Add @databases

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Consola can be compared to Pino but it supports easier Mocking, as well as Pausing/Resuming the logs and redirecting the `console.log` to `consola`.
See more https://github.com/nuxt/consola

Add consola

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Cashify is a lightweight currency conversion library. I created it, because the popular [money.js](https://github.com/openexchangerates/money.js) package:
- is not maintained (last commit was ~5 years ago)
- has over 20 open issues
- does not support TypeScript
- has implicit globals
- does not have any unit tests
- Simple API
- 0 dependencies
- Actively maintained
- Well tested
- [Easy migration from money.js](https://github.com/xxczaki/cashify#migrating-from-moneyjs) …

Add cashify

---

readme.md

Add genepi

---

readme.md

Suggesting the addition of CodeSandbox as it's more full-featured than any of the other similar dev tools listed.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add CodeSandbox

---

readme.md

Added playwright on testing
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Added `Playwright` under Testing. The UI Automation tool for Chromium, WebKit and Firefox browsers with a single API created by Microsoft.

Add Playwright

---

readme.md

Request is deprecated (request/request#3142)
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Remove request

---

readme.md

Docusaurus create a website with Markdown + React.js.
Feature: 
- Document Versioning: Support users on all versions of your project. Document versioning helps you keep documentation in sync with project releases
- Document Search: Make it easy for your community to find what they need in your documentation (Algolia DocSearch)
- Translations: Localization comes pre-configured (Crowdin )

Add Docusaurus

---

readme.md

Add patch-package

---

readme.md

Hi,
I am Branko and I work for Manning Publications.
I though this video course of ours might be a good contribution to your list.
Thanks for considering it!

Add Mastering REST APIs in Node.js: Zero-To-Hero

---

readme.md

Update description for Sequelize

---

readme.md

Add StegCloak

---

readme.md

Add axe-core

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
The pipcook is a front-end algorithm framework to create a ML pipeline based on tfjs-node in JavaScript, and it's included in tfjs gallery: https://github.com/tensorflow/tfjs/blob/master/GALLERY.md
GitHub: https://github.com/alibaba/pipcook

Add pipcook

---

readme.md

website is parked, project seems to be dead
Fixes #1049
Closes #1051
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Remove RequireBin

---

readme.md

:wave: I decided to update the description of my OAuth client, that I initially added to this list in 2015 https://github.com/sindresorhus/awesome-nodejs/pull/230
A lot have changed since then, and so I though that it might be useful to outline the key selling points as of today, because that might be useful information for anyone searching for such solution.
Main difference is that [Grant](https://github.com/simov/grant) now ships with 4 serverless handlers, making it a viable solution for Lambda Functions, and then I also added a handler for Fastify.

Update description for Grant package

---

readme.md

It was inspired by tools like django admin, railsadmin and active admin. It reached 2k stars this weekend so I decided that this is the right moment to post it here.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add AdminBro

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
tinyhttp is a modern Express-like web framework for Node.js, written in TypeScript and compiled to native ESM. It uses a bare minimum amount of dependencies trying to avoid legacy hell.
:earth_africa:  Website: https://tinyhttp.v1rtl.site
:octocat:  Repo: https://github.com/talentlessguy/tinyhttp
the project itself, at the moment of adding this PR, has 268 stars and 8 (including myself) contributors. Was created on June 13, so more than 30 days passed.
I used the …

Add Tinyhttp

---

readme.md

✅
Hey there 👋🏼
Created this PR to add Prisma to the list of ORMs. While Prisma is not actually an ORM, it aims to solve the same problems.
Since there are so many ORMs in the landscape, I'll share a bit about what makes Prisma different
Unlike ORMs, with Prisma you don't create model classes nor do you map fields in your codebase to database fields. Instead, you use the generated Prisma Client API as a type-safe query builder that returns plain JavaScript objects. Schema changes …

Add Prisma

---

readme.md

Thanks for the help @sindresorhus!
This reverts #1071.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Remove link to Netlify job description

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Name: `superstruct`
GitHub: https://github.com/ianstormtaylor/superstruct
Yarn: https://yarnpkg.com/package/superstruct
NPM: https://www.npmjs.com/package/superstruct
Stars: 4.6k
Downloads: 733.3k / mo
Superstruct makes it easy to define interfaces and then validate JavaScript data against them. Its type annotation API was inspired by Typescript, Flow, Go, and GraphQL, giving it a familiar and easy to understand API.
But Superstruct is designed for validating data at …

Add Superstruct

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
github: https://github.com/marblejs/marble
website: https://docs.marblejs.com/
Pretty famous functional node js framework for server side apps.

Add Marble.js

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
[https://github.com/nut-tree/nut.js](https://github.com/nut-tree/nut.js) is cross-platform desktop automation framework which supports macOS, Linux and Windows. It is easy to install and supports node 10.x to 14.x as well as Electron.
With nut.js it is possible to fully automate your desktop by simulating mouse / keyboard input. Additionally, it supports on-screen image search for advanced interactions as well as possibilities to retrieve infos about open windows. …

Add nut.js

---

readme.md

**Link** 
https://github.com/testcontainers/testcontainers-node
**Why it should be included:**
Real integration testing using Docker:
```javascript
const redis = require("async-redis");
const { GenericContainer } = require("testcontainers");
describe("GenericContainer", () => {
let container;
let redisClient;
beforeAll(async () => {
container = await new GenericContainer("redis")
.withExposedPorts(6379)
.start();
redisClient = redis.createClient(
container.getMappedPort(6379),
container.getHost(),
);
});
afterAll(async () => {
await redisClient.quit();
await container.stop();
});
it("works", async () => {
await redisClient.set("key", "val");
expect(await redisClient.get("key")).toBe("val");
});
});
```

Add testcontainers-node

---

readme.md

Update link to Chevrotain

---

readme.md

Added https://github.com/thlorenz/v8-perf
---
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add v8-perf link

---

readme.md

Added some video links so that `awesome-nodejs` can be effective for understanding Node.js internals.
---
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add some videos about V8 and libuv

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
I have added a couple of books to the list.
Full disclaimer: I am co-author of Node.js design patterns. I hope you don't mind this.

Add two Node.js books

---

readme.md

project seems to be abandoned, no activity in commits, issues, pr's, etc.
https://github.com/sfast/zeronode
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Remove zeronode

---

readme.md

Added https://github.com/matmen/ImageScript
JavaScript image manipulation utilizing WebAssembly and direct buffer access for performance
Works in Node, Deno and all modern browsers
---
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add ImageScript

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
It's a REST API client library written from scratch that delivery high performance implementing HTTP/1.1 specification.

Add undici

---

readme.md

Add Notifire

---

readme.md

:wave: I decided to submit one of my projects called **[Purest](https://github.com/simov/purest)**.
It's a REST API client library for creating REST API client libraries that I initially released 7 years ago, but only now I feel like it's in a shape I like. Last week I released a new major v4 and also an article about it https://dev.to/simov/purest-53k0.
Purest is basically yet another HTTP client for Node.js, but with a unique twist and expressive API on top, that you can also customize to your liking.

Add purest

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
bullmq is the successor of bull ([Top item in the job queue)](https://github.com/sindresorhus/awesome-nodejs/blob/main/readme.md?plain=1#L733) it provides more features and written in typescript

add bullmq to jobs queue

---

readme.md

This adds [`wild-wild-path`](https://github.com/ehmicky/wild-wild-path).
This library provides with CRUD (get/has/list/set/remove) operations on object properties using not only dot-delimited paths but also wildcards (`*` and `**`), regular expressions, array slices and unions. 
---
By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md?rgh-link-date=2022-04-07T08%3A34%3A59Z) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. :vulcan_salute: 
:arrow_up::arrow_up::arrow_up::arrow_up::arrow_up::arrow_up::arrow_up::arrow_up::arrow_up:

Add `wild-wild-path`

---

readme.md

Add new section for packages managers.

feat: add package manager section

---

.github/pull_request_template.md

Fix link on PR Template

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Amplication is an open‑source development tool. It helps professional Node.js developers develop quality Node.js applications without spending time on repetitive coding tasks.
Amplication auto-generates backend apps built with TypeScript and Node.js, and a client built with React.

add Amplication

---

readme.md

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
This PR adds a Node.JS course by Drew Karriker

Adds Kinsta's Node.JS Course

---

readme.md

Added modbus-serial under Hardware

---

readme.md

Hi there! Thanks for running this awesome list.
This PR is to add [NAPI-RS ](https://napi.rs/) to a new "cross-platform integration" section.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Add Napi-RS under new category (cross-platform integration)

---

readme.md

Hi thanks for running this awesome list.
This PR is to add Graphweaver to CMS section. 
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Added Graphweaver

---

readme.md

Add [zod](https://github.com/colinhacks/zod) - TypeScript-first schema validation with static type inference.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Added zod under Data validation

---

readme.md

With over 20K+ stars on GH, Drizzle is an absolute must have on this list of **awesome** pkgs. 🎉
https://github.com/drizzle-team/drizzle-orm

Added Drizzle to list of ODM / ORM

---

readme.md

I really enjoyed using this project, nice work! Caught a couple of typos in the README though 😛
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

Update README.md, fix a typo

---

readme.md

This reverts https://github.com/sindresorhus/awesome-nodejs/commit/55417c7044aec70e9bf9c7decb00afe766cb4fff.
Backgrounds:
- https://github.com/community/maintainers/discussions/442#discussioncomment-12401989
- https://x.com/kossnocorp/status/1795300115567067270

Remove a fake link

---

readme.md

removed gm (imagemagick wrapper) for it has been sunset
