sindresorhus/awesome-nodejs

- readme.md
Ramda grew into a serious, popular Functional Programming Library in recent months. Got already ~1500 stars on Github: https://github.com/ramda/ramda
It doesn't have as many built-in functions like Lo-Dash, but the way it enables functional composition is often more concise.
For example instead of chaining one usually uses R.compose or R.pipe and then plugs in different Ramda functions (which are automatically curried) OR user-built functions. Ramda functions and user-built functions are treated equally, as oppose to chaining.
> Add Ramda as Functional Programming Library

- readme.md
[Demo](http://markdown-it.github.io/linkify-it/) :)
Did this, because could not find good link recogniser for node, configurable, with full unicode support and so on. See readme. I think, this one is much more advanced than existings.
> Added linkify-it (links recogniser)

- readme.md
Hello, I would like to add `dotenv` project to Miscellaneous section.
It is a good practice to pass application configuration (e.g. db connection strings) via environment variables (12-factor app). But when you develop an application it won't be convenient to type all environment variables in terminal to launch your application (unless you are using some process management tool, however, that requires additional configuration). That's where `dotenv` project comes out. You can put all env. variables stuff in one file (`.env`) and load it with one line of code.
> Add dotenv to Miscellaneous section

- readme.md
The latest version of the github-linker also links dependencies in .js, .jsx, .coffee and .md files.
> extend github-linker description

- readme.md
https://github.com/runvnc/modhelp
> modhelp (Syntax highlighted node module readmes in terminal with ANSI-friendly pager)

- readme.md
[navit](https://github.com/nodeca/navit) is  similar to [Nightmare](https://github.com/segmentio/nightmare) from your list, but has much more consistent API (including intermediate errors handle) and better phantomjs bridge. Don't know is it strong enougth for this list. But i'm sure you will see a big difference if start to use.
> Add `navit`, remove `Nightmare`

- readme.md
List [async-chainable](https://github.com/hash-bang/async-chainable) under Control Flows section.
> Added async-chainable

- readme.md
When comparing [`node_redis`](https://github.com/NodeRedis/node_redis) with [`ioredis`](https://github.com/luin/ioredis) I think that the latter is better under every aspect.
It is faster, it has sane error handling, it has great features like the ability to define a custom command from a lua script and it is well maintained.
Right now I would recommend it instead of `node_redis`.
> Remove node_redis in favor of ioredis

- readme.md
https://github.com/fivdi/i2c-bus
This package allows you to access any type of I2C device like accelerometers, compasses, and temperature sensors on single-board computers like the Raspberry Pi.
> Add i2c-bus

- readme.md
This extension was mentioned in a recent NodeUp episode as an awesome tool for package discovery.
Definitely belongs here.
> Add link to npm-hub extension

- readme.md
This adds [ttystudio](https://github.com/chjj/ttystudio).
> ttystudio differs from other terminal recorders in that:
>
> 1. It has its own built-in gif and apng writer, no imagemagick required. The writer now has built-in frame offset optimization.
> 2. It has a font parser to render the font during image writing so no terminal playback is required when writing the image (this also means no GUI is required at all - you can record on a remote machine via ssh).
> 3. No concatenation of hundreds of gif files required. ttystudio automatically writes out to one gif or apng.
> 4. No glitchy frames due to imperfect GUI recording of the playback or gif concatenation.
ttystudio will record frames even if nothing is being updated on the screen.
> Add ttystudio to Command-line apps

- readme.md
Returns native Promise (if available) or [pinkie](http://github.com/floatdrop/pinkie) polyfill for ES6 Promise.
> Add pinkie-promise ES6 Promise ponyfill

- readme.md
Added [bluebird-co](https://github.com/novacrazy/bluebird-co) to readme. It's a high performance reimplementation of tj/co using yield handlers for [Bluebird coroutines](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisecoroutinegeneratorfunction-generatorfunction---function) to handle asynchronous generators.
> Added bluebird-co

- readme.md
https://github.com/marko-js/marko
marko has some unique and awesome features:
- [Extremely fast](https://github.com/marko-js/templating-benchmarks)
- Lightweight (~3.75KB gzipped)
- Clean HTML syntax
- Custom tags and custom attributes
- Streaming, async and progressive HTML rendering
- Compiles templates to CommonJS modules that are [readable and debuggable](https://gist.github.com/patrick-steele-idem/0514b480219d1c9ed8d4)
- Server-side and client-side rendering (compatible with JavaScript module bundlers)
- Friendly compile-time error messages
- Can be used with [marko-widgets](https://github.com/marko-js/marko-widgets) for building stateful UI components with DOM diffing/patch, event delegation and declarative event binding
Sample template:
```xml
Hello ${data.name}!
<ul …
```
> Add `marko` to `Templating`

- readme.md
https://github.com/nodeca/probe-image-size
This package is useful for content generation, when you need to quickly detect the size of remote images. It starts download and immediately stops when got enougth info to detect image type and size.
We did it, because alternate implementations are outdated (fewer types support / pending PRs / memory use / ...). I think, this one is the most comfortable for developpers.
> Add `probe-image-size`

- readme.md
I made a FAQ for streams that tries to address some common, real-world, production use cases, where left to the Node.js manual and google, you'd be lost.
https://github.com/stephenplusplus/stream-faqs
Hope this is the right fit, and the right category! (Cheatsheets?)
> Add `stream-faqs`

- readme.md
https://github.com/nodeca/url-unshort
Expand shortened URLs
https://github.com/nodeca/embedza
Create snippets by URL. Useful for content builders to replace youtube links with players, replace URL-s with page titles and so on. Configurable.
> Add `url-unshort` and `embedza`

- readme.md
This adds [console-log-level](https://github.com/watson/console-log-level).
I'm not sure if it is a good candidate for the list but sometimes I only want a very simple logger.
`console-log-level` supports, imho, the only two features that are missing in the native `console` object to be a viable logger:
- the ability to set a log level.
- the ability to set a custom prefix for all log messages.
> Add console-log-level to Logging

- readme.md
Small, simple module that formats a long string into a hanging-indented paragraph with newlines and indentations. Breaks lines in between words. Configurable max line length and indentation size.
I believe this functionality is unique among the modules currently in the text section.
> add hanging-indent

- readme.md
Added [dev-time](https://github.com/samverschueren/dev-time-cli) to the list of command line apps.
> add dev-time-cli

- readme.md
[diff2html-cli](https://github.com/rtfpessoa/diff2html-cli) is an easy to use command-line application that creates pretty HTML diffs from git diff outputs, allowing a better code comparison in the browser.
> Add diff2html-cli to Command-line apps

- readme.md
Saw `pify` in the list, so added [rfpify](https://github.com/samverschueren/rfpify) as well. Don't feel bad if you reject the PR :).
> add rfpify

- readme.md
Bell.js is [no longer maintained](https://github.com/eleme/bell.js), and banshee is the [recommended
replacement](https://godoc.org/github.com/eleme/banshee#hdr-Migrate_from_bell).  As such, list banshee in bell's place.
> Replace bell with banshee

- readme.md
It is important to prevent ReDoS attacks. Here is a CLI tool to identify possible regex denial of service (ReDos) vulnerabilities in your project.
> Add RegEx-DoS

- readme.md
This adds [google-libphonenumber](https://github.com/seegno/google-libphonenumber), a library to parse, format  and validate international phone numbers.
> Add google-libphonenumber to Parsing

- readme.md
Hey,
I just noticed that agenda is under "Miscellaneous" instead of "Job Queues".
If there is a specific reasoning behind this I would love to know.
Thank you,
Atrox
> Move agenda to job queues section

- readme.md
Adds a link to the Microsoft Node.js Guidelines under miscellaneous (I work on Node.js at Microsoft.) These guidelines help developers work with Node.js on Microsoft platforms, including Windows and Azure.
> Add Microsoft Node.js Guidelines

- readme.md
This adds [valvelet](https://github.com/lpinca/valvelet), a small utility to limit the execution rate of a function. It works seamlessly with promise-returning functions. It is useful for scenarios such as REST APIs consumption where the amount of requests per unit of time should not exceed a given threshold.
> Add valvelet

- readme.md
https://github.com/nodeca/idoit (job queue)
I know you like clear & short package descriptions, but don't know how to explain everything in one phrase because topic is complicated. Here are details:
- package is inspired by Celery & Akka ideas
- tasks can be chained & grouped
- special "iterator" feature to generate chunks for huge ranges on demand
- in short - allows avoid "skip" in db selects when you need to create chunks of equal size. "skip"-s are very slow on huge sets. This feature is unique for this package.
- worker pools instead of "priorities" - no reinventing system scheduler to separate heavy tasks.
- "transactional" redis updates - data is guaranteed to be eventually consistent. That's not as easy as it seems.
Of cause, popular features like sheduler, postponed execution and …
> Add idoit to Job queues section

- readme.md
[lessmd](https://lessmd.js.org/) is often used for converting mardown into highlighted document for terminal, as well as a cli pager (viewer) for markdown.
> Add lessmd

- readme.md
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
1. Run a localhost webapp / webservice (may be express app)
2. Run localtunnel on the express app port using 
`lt --port <port>`
3. A unique url is generated to share your webservice to the world.
`https://<sub-domain>.localtunnel.me`
4. Share the url and your express app is exposed to everyone. Useful for demonstrations. Enjoy
> Add localtunnel

- readme.md
https://github.com/nodeca/unhomoglyph
This package "normalize" string look by replace all homoglyphs with base characters (`AΑАᎪᗅᴀꓮ` -> `AAAAAAA`).
That's useful to detect similar strings. For example, if you wish to prohibit "duplicates" with confusing nicknames and so on.
> Add unhomoglyph

- readme.md
Pino has moved into an organization. This PR updates the link to reflect that.
> Update link to Pino logger

- readme.md
[pigpio](https://github.com/fivdi/pigpio) makes things possible on the Raspberry Pi that are typically not possible, for example, PWM and Servo pulses on any number of GPIOs simultaneously.
> Add pigpio

- readme.md
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Just updating the MySQL client link from https://github.com/felixge/node-mysql to https://github.com/mysqljs/mysql (GitHub already does this redirect)
> Update MySQL driver URL

- readme.md
ubolonton/js-csp is alive, not the other one.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
> Update repo for js-csp

- readme.md
The `nar` module is deprecated and suggests the `pkg` module which is already in the list.
> Remove deprecated module `nar`

- readme.md
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it.**
[gradient-string](https://github.com/bokub/gradient-string) is a package allowing to display colorful strings in the terminal stdout. However, unlike other packages such as chalk, `gradient-string` is focused on __gradients only__ (and actually uses chalk to color each letter individually).
As far as I know, gradient-string is the only package allowing to color stdout with gradients, making it unique and awesome.
[![gradient-string](http://bit.ly/2tlmSgL)](http://bit.ly/2tlhNFv)
> Add gradient-string

- readme.md
`svg-term-cli` is a tool to generate SVGs of terminal sessions recorded via `asciinema`. 
The files are animated via CSS, so the animation plays where JavaScript delivery is not possible, such as NPM or GitHub markdown renderings. 
* Reference: https://github.com/sindresorhus/ora/pull/66#issuecomment-354452180
> Add svg-term-cli

- readme.md
I've followed @sindresorhus suggestion in https://github.com/sindresorhus/awesome-nodejs/pull/730
and I've refactored `credential-plus` and renamed it to `upash`.
Project page:
https://github.com/simonepri/upash
This PR updates the name, the url and the description inside the list.
> Rename credential-plus to upash

- readme.md
Leaving Nock in the test-section, writing Nock with uppercase (as used in the project's [readme](https://github.com/node-nock/nock#nock))
> Deduplicate Nock-entry

- readme.md
URL had a duplicate `h` in `https` (was `hhttps`) and didn't work.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
> Correct broken URL to KeystoneJS

- readme.md
Because Babylon has been moved into the main Babel mono-repo as `@babel/parser`.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
> Fix dead link to babel-parser

- readme.md
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
I clicked on Podcasts section of Resources and it was just hyperlinked and going nowhere, it can be added back if someone wants to add links related to podcasts.
> Remove `Podcasts` from TOC as it doesn't exist

- readme.md
This requests adds [Cliffy](https://github.com/drew-y/cliffy) to the Command-line utilities section.
[Cliffy](https://github.com/drew-y/cliffy) is an alternative to [Vorpal](https://github.com/dthree/vorpal).
Compared with Vorpal, Cliffy provides:
- Active Maintenance (Vorpal's last release was in 2015)
- Can parse negative numbers as parameters
- Typed parameters
- Typescript support
- Custom input / output streams
> Add Cliffy

- readme.md
[Discharge](https://github.com/brandonweiss/discharge) is, as far as I’m aware, the easiest way to deploy static websites to Amazon S3. It can also configure an SSL certificate and distribute the site via CloudFront, all without having to know anything about AWS. I spent hours poring over AWS’s terrible docs so no one else would have to. There is also a prompt-based UI to help you configure it. And it’s very well documented.
Thanks for considering!
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
> Add discharge

- readme.md
As seen in [this issue](https://github.com/stackgl/stackgl.github.io/issues/11#issuecomment-416407375) on their repo, the URL for StackGL has changed.
> Update stackgl link

- readme.md
In *contributing.md*:
> Link to the GitHub repo, not npmjs.com or its website.
I update link repo instead of its website.
But `stackgl` and `nodeschool` include much repo so I use the link of its organization.
Should I use the old link?
> Update links to point to repos instead of websites

- readme.md
[Charge](https://charge.js.org) is an opinionated, zero-config static site generator. It uses JSX and MDX for templating. CSS is post-processed with PostCSS. JavaScript is transpiled with Babel. You can import any type of module from npm without having to worry about what format it uses. You don’t have to define “entrypoints” or where dependencies are located—it just figures it all out for you and does the right thing. It hopefully works exactly how you’d expect it to. And last, it doesn’t serve React to the front-end like many popular React-based static site generators, which is usually overkill for small sites.
I didn’t really want to build this. If you’d asked me a while ago, I would have said the last thing the world needs is another static site generator. But when I went hunting for …
> Add Charge

- readme.md
https://github.com/ai/nanoid is an actively maintained id-generator which compares best to UUIDv4 (random-based id generation) which generates ids with a similar collision probability, but less size (21 symbols vs 36) and ~16% faster. It has security in mind (using crypts random number generator and providing a company-backed disclosure procedure.
It is very helpful at any point heavily relying on collision-free ids, like f.e. cassandra or couchdb document-ids.
I don't know if mad science is the best category.
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have …
> Add nanoid

- readme.md
https://github.com/sheerun/modern-node
> For CLI tools, the bar is especially high, and unless it's something very awesome
I think it's awesome through the roof but it's up to you to decide :P
This project is similar just to your boilerplate but works differently:
1. It's not meant for cloning but installing or creating with `create-modern-node`
2. It uses jest instead of ava, it uses prettier+eslint+standard instead of xo
3. It has built in precommit hook so installing husky is not necessary
I've put it next to your package instead of at the bottom because these two are most similar in functionality.
> Add modern-node

- readme.md
TypeScript ORM, heavily inspired by doctrine, based on Data Mapper, Unit of Work and Identity Map patterns. Also works with vanilla JS.
If I should argue about differences with existing projects, TypeORM would be probably closest, but it does not implement Unit of Work and Identity Map patterns, so that is the key difference here.
repository: https://github.com/mikro-orm/mikro-orm
website/docs: https://mikro-orm.io
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
> Add MikroORM

- readme.md
The CloudRail project has now been discontinued as per their [README](https://github.com/CloudRail/cloudrail-si-node-sdk):
> We decided to discontinue this product as of February 2019. CloudRail now entirely focuses on connecting industrial sensors to AWS, Azure, Google IoT and many more to realize IIoT projects. Learn more at https://cloudrail.com
> Remove CloudRail

- readme.md
As discussed with @sindresorhus, this is adding a link to a job description for a Node.js senior backend position at Netlify.
> Add link to Netlify job description

- readme.md
Hi !
Would you consider adding [pg-mem](https://github.com/oguimbal/pg-mem) to this list ?
It's a pure js in-memory postgres database emulator easing unit/integration testing.
It also implements [adapters](https://github.com/oguimbal/pg-mem/wiki/Libraries-adapters) which allow to wrap an in-memory db to some [awesome nodejs db libs](https://github.com/sindresorhus/awesome-nodejs#database).
👉 [Play with it here](https://oguimbal.github.io/pg-mem-playground/)
When testing code that use a db, you usually have to choose between those options :
- Mock all your requests... this is quite painful,  doesnt work for end-to-end tests, and locks-down implementation details.
- Run a real clean instance of your db by running your tests in docker... this has a really high overhead, and is hard to setup. …
> Add pg-mem

- readme.md
- Updated link points new Loopback 4.
- Old link was pointing to Loopback 3 which has reached End Of Life.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
> Update Loopback framework link

- readme.md
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
This client aims to have a simple [statsd](https://github.com/statsd/statsd) compliant API with some optional flavour for advanced usage, like buffered metrics, namespacing, DNS cache and either UDP/TCP transports.
[Link to the project](https://github.com/immobiliare/dats)
> Add `dats`

- .github/workflows/links.yml
Every Sunday at midnight this Github action will validate that all
http/https links responds with 200. If a link has been permanently
removed (or just moved) it can be removed/changed which leads to a
higher quality list.
This check is already in place in the mac-setup[0] repo and is working
well. It won't prevent any PRs from getting merged, and optionally a
badge can be added to the README to highlight the link status (see
mac-setup repo).
[0]: https://github.com/sb2nov/mac-setup/
---
Hi @sindresorhus! I'm curious what you think of my suggestion. I think this will increase the quality of this nice repo! 🙂 It will make commits like [this one](https://github.com/sindresorhus/awesome-nodejs/commit/041a511ee4ab86b2069a2071d1e89abdc38a040d) easier to create as the workflow will figure out …
> Validate that links are up (once a week)

- readme.md
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
There's currently no guide on scaling Node apps in production on the list so this article adds one to the **Tutorials** section. Thanks for the consideration!
> Add Scaling Node.js guides to tutorials

- readme.md
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Two broken links:
I changed these links with these two:
If you want anything changed, please don't hesitate to ask!
Fixes #1239
> #1239 - fixed broken links

- readme.md
listr is not maintained anymore, listr2 is a fork up-to-date and maintained
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
> Replace listr by listr2

- readme.md
Added Hono web framework
Github link: https://github.com/honojs/hono
Offical website: https://hono.dev/
Why to include:
Hone is new modern web framework which cab be used in multiple JS runtimes like Nodejs, Deno, Bun, Cloudflare workers. It is one of the fasted framework which is built on web Request and Response.
> Add Hono web framework

- readme.md
https://github.com/ipfs/js-ipfs is depreciated and superseded by Helia
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
> link update

- readme.md
Hi there 👋   We've added @breejs to the list of job queues.  We formerly maintained Agenda (which is listed) and currently use Bree in production for 500,000+ domain names in our email service @forwardemail.  We'd love to see Bree added to the list!  It has types, tests, spawned sandboxed processes, supports async/await, retries, throttling, concurrency, and cancelable jobs with graceful shutdown.  Additional docs are at <https://jobscheduler.net>.  Thank you! 🙏
> feat: added bree to job queues

- readme.md
Edge.js link was a dead repo (last updated 6 years ago).
I have only replaced that one link with an active fork - https://github.com/agracio/edge-js
No other changes were done. Thanks.
> Replace edge.js with active fork

- readme.md
Adds [Vitest](https://github.com/vitest-dev/vitest) to the Testing section.
Vitest has become a popular modern testing framework in the Node.js ecosystem with:
- **700k+ weekly downloads** on npm
- **32k+ stars** on GitHub  
- Native ESM and TypeScript support
- Jest-compatible APIs for easy migration
- Blazing fast performance powered by Vite
- Built-in component testing for Vue/React
- Parallel test execution and snapshot testing
Added alphabetically after Jest in the Testing section, as it's often considered a modern alternative to Jest.
Closes any related issues about missing Vitest in the testing tools list.
> Add Vitest to testing frameworks
